# 开发环境配置
app:
  port: 3000
  # 日志相关
  logger: 
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: '../logs'
swagger:
  enabled: true
  path: api-doc
db:
  mysql:
    DATABASE_URL: "mysql://root:123456@localhost:3306/mock-api-serve?schema=public"