name: Docker Build and Push

# 触发条件
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# 定义环境变量
env:
  IMAGE_NAME: mock-app-server
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ACCOUNT: ${{ srecs.DOCKER_ACCOUNT }}
  DOCKER_ACCOUNT_PASSWORD: ${{ secrets.DOCKER_ACCOUNT_PASSWORD }}
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  REMOTE_HOST_PASSWORD: ${{ secrets.REMOTE_HOST_PASSWORD }}

# 定义任务
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # 3. 拉取docker buildx 构建工具
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 构建 Docker 镜像并推送
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME}}:latest
          platforms: linux/amd64,linux/arm64

      # 4. 推送 Docker 镜像到 Docker Hub
      - name: ssh remote
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}        
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: "root"
        script: |
            cd /mock-app-server/
            ./restart_service.sh